// spawn_sidecar.cc — see spawn_sidecar.h for contract.
//
// Design notes:
//   - We use posix_spawn (not fork+execve) because it is async-signal-safe,
//     avoids copying the CEF/GTK main-loop tables, and is supported on all
//     Linux distros since glibc 2.0.
//   - The capability token is generated by reading 32 bytes from
//     /dev/urandom and base64url-encoding them (no padding, lowercase + -/_).
//     The host generates the token; the sidecar must echo it in hello.
//   - The runtime directory uses $XDG_RUNTIME_DIR when present (default
//     /run/user/<uid>) and falls back to $TMPDIR/wails-<uid>.
//   - The handshake reads exactly one frame from the accepted fd, validates
//     the envelope, then writes a ready envelope. We use a short
//     recv/send timeout so a stuck sidecar does not block host startup.
//   - SO_PEERCRED is the authoritative UID check; the capability is the
//     authentication secret. Either alone would be insufficient.

#include "spawn_sidecar.h"

#include <algorithm>
#include <cerrno>
#include <climits>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fcntl.h>
#include <fstream>
#include <random>
#include <signal.h>
#include <spawn.h>
#include <string>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/un.h>
#include <sys/wait.h>
#include <unistd.h>
#include <vector>

extern char** environ;

namespace wails_cef {

namespace {

constexpr const char* kBase64UrlChars =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";

std::string Base64UrlEncode(const std::vector<uint8_t>& bytes) {
    std::string out;
    out.reserve(((bytes.size() + 2) / 3) * 4);
    size_t i = 0;
    while (i + 3 <= bytes.size()) {
        uint32_t v = (uint32_t(bytes[i]) << 16) | (uint32_t(bytes[i + 1]) << 8) | uint32_t(bytes[i + 2]);
        out.push_back(kBase64UrlChars[(v >> 18) & 0x3F]);
        out.push_back(kBase64UrlChars[(v >> 12) & 0x3F]);
        out.push_back(kBase64UrlChars[(v >> 6) & 0x3F]);
        out.push_back(kBase64UrlChars[v & 0x3F]);
        i += 3;
    }
    if (i < bytes.size()) {
        uint32_t v = uint32_t(bytes[i]) << 16;
        if (i + 1 < bytes.size()) v |= uint32_t(bytes[i + 1]) << 8;
        out.push_back(kBase64UrlChars[(v >> 18) & 0x3F]);
        out.push_back(kBase64UrlChars[(v >> 12) & 0x3F]);
        if (i + 1 < bytes.size()) {
            out.push_back(kBase64UrlChars[(v >> 6) & 0x3F]);
        }
    }
    return out;
}

bool ReadRandomBytes(void* buf, size_t n) {
    std::ifstream f("/dev/urandom", std::ios::binary);
    if (!f) return false;
    f.read(static_cast<char*>(buf), n);
    return f.gcount() == static_cast<std::streamsize>(n);
}

std::string HexFromRandom(size_t bytes) {
    std::vector<uint8_t> b(bytes);
    if (!ReadRandomBytes(b.data(), bytes)) return {};
    static const char* hex = "0123456789abcdef";
    std::string out;
    out.reserve(bytes * 2);
    for (auto v : b) {
        out.push_back(hex[(v >> 4) & 0xF]);
        out.push_back(hex[v & 0xF]);
    }
    return out;
}

bool PathExists(const std::string& p) {
    struct stat st;
    return stat(p.c_str(), &st) == 0;
}

bool IsExecutableFile(const std::string& p) {
    struct stat st;
    if (stat(p.c_str(), &st) != 0) return false;
    return S_ISREG(st.st_mode) && (st.st_mode & S_IXUSR);
}

std::string Dirname(const std::string& path) {
    auto pos = path.find_last_of('/');
    if (pos == std::string::npos) return ".";
    if (pos == 0) return "/";
    return path.substr(0, pos);
}

std::string ReadEnv(const char* key) {
    const char* v = std::getenv(key);
    return v ? std::string(v) : std::string();
}

int SetSocketTimeout(int fd, int seconds) {
    struct timeval tv;
    tv.tv_sec = seconds;
    tv.tv_usec = 0;
    if (setsockopt(fd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv)) < 0) return -1;
    if (setsockopt(fd, SOL_SOCKET, SO_SNDTIMEO, &tv, sizeof(tv)) < 0) return -1;
    return 0;
}

bool SendFrame(int fd, const std::string& frame) {
    if (frame.size() > 16 * 1024 * 1024) return false;
    uint32_t len = static_cast<uint32_t>(frame.size());
    uint8_t header[4];
    header[0] = (len >> 24) & 0xFF;
    header[1] = (len >> 16) & 0xFF;
    header[2] = (len >> 8) & 0xFF;
    header[3] = len & 0xFF;

    std::string msg;
    msg.reserve(4 + frame.size());
    msg.append(reinterpret_cast<const char*>(header), 4);
    msg.append(frame);

    size_t written = 0;
    while (written < msg.size()) {
        ssize_t n = write(fd, msg.data() + written, msg.size() - written);
        if (n < 0) {
            if (errno == EINTR) continue;
            return false;
        }
        if (n == 0) return false;
        written += n;
    }
    return true;
}

bool RecvFrame(int fd, std::string* out, std::string* err) {
    uint8_t header[4];
    ssize_t n = recv(fd, header, 4, MSG_WAITALL);
    if (n <= 0) {
        if (err) *err = "peer closed before sending frame";
        return false;
    }
    uint32_t len = (uint32_t(header[0]) << 24) | (uint32_t(header[1]) << 16) |
                   (uint32_t(header[2]) << 8) | uint32_t(header[3]);
    if (len > 16 * 1024 * 1024) {
        if (err) *err = "frame too large: " + std::to_string(len);
        return false;
    }
    out->resize(len);
    size_t received = 0;
    while (received < len) {
        n = recv(fd, out->data() + received, len - received, MSG_WAITALL);
        if (n <= 0) {
            if (err) *err = "peer closed mid-frame";
            return false;
        }
        received += n;
    }
    return true;
}

std::string ExtractJsonString(const std::string& json, const std::string& key) {
    auto pos = json.find("\"" + key + "\"");
    if (pos == std::string::npos) return {};
    pos = json.find(':', pos);
    if (pos == std::string::npos) return {};
    pos++;
    while (pos < json.size() && (json[pos] == ' ' || json[pos] == '\t')) pos++;
    if (pos >= json.size() || json[pos] != '"') return {};
    pos++;
    std::string out;
    while (pos < json.size() && json[pos] != '"') {
        if (json[pos] == '\\' && pos + 1 < json.size()) {
            out.push_back(json[pos + 1]);
            pos += 2;
        } else {
            out.push_back(json[pos]);
            pos++;
        }
    }
    return out;
}

}  // namespace

std::string GenerateCapabilityToken() {
    std::vector<uint8_t> b(32);
    if (!ReadRandomBytes(b.data(), b.size())) {
        return {};
    }
    return Base64UrlEncode(b);
}

std::string CreateRuntimeDir() {
    std::string base = ReadEnv("XDG_RUNTIME_DIR");
    if (base.empty() || !PathExists(base)) {
        base = "/tmp";
    }
    std::string uuid = HexFromRandom(16);
    if (uuid.empty()) return {};
    std::string path = base + "/wails-" + uuid;
    if (mkdir(path.c_str(), 0700) != 0 && errno != EEXIST) {
        return {};
    }
    return path;
}

int BindSidecarSocket(const std::string& runtime_dir, std::string* socket_path) {
    if (socket_path) *socket_path = runtime_dir + "/host.sock";
    std::string sp = socket_path ? *socket_path : runtime_dir + "/host.sock";

    unlink(sp.c_str());

    int fd = socket(AF_UNIX, SOCK_STREAM, 0);
    if (fd < 0) return -1;

    // FD_CLOEXEC so the socket never leaks into the sidecar child.
    int flags = fcntl(fd, F_GETFD, 0);
    if (flags >= 0) fcntl(fd, F_SETFD, flags | FD_CLOEXEC);

    struct sockaddr_un addr;
    memset(&addr, 0, sizeof(addr));
    addr.sun_family = AF_UNIX;
    strncpy(addr.sun_path, sp.c_str(), sizeof(addr.sun_path) - 1);

    if (bind(fd, reinterpret_cast<struct sockaddr*>(&addr), sizeof(addr)) < 0) {
        close(fd);
        return -1;
    }
    if (listen(fd, 5) < 0) {
        close(fd);
        unlink(sp.c_str());
        return -1;
    }
    chmod(sp.c_str(), 0600);
    return fd;
}

std::string FindSidecarBinary(const std::string& argv0_path) {
    if (const char* env = std::getenv("WAILS_CEF_SIDECAR")) {
        if (IsExecutableFile(env)) return env;
    }
    // Allow override via argv0-adjacent convention: <argv0_dir>/wails-go-runtime.
    if (!argv0_path.empty()) {
        std::string candidate = Dirname(argv0_path) + "/wails-go-runtime";
        if (IsExecutableFile(candidate)) return candidate;
    }
    // Fall back to CEF_DIR/wails-go-runtime.
    if (const char* cef_dir = std::getenv("CEF_DIR")) {
        std::string candidate = std::string(cef_dir) + "/wails-go-runtime";
        if (IsExecutableFile(candidate)) return candidate;
    }
    return {};
}

pid_t SpawnSidecar(const std::string& binary_path,
                   const std::string& socket_path,
                   const std::string& capability,
                   const std::string& assets_dir,
                   std::string* err) {
    // argv = binary, --cef-host-socket, <sp>, --cef-host-capability, <cap>,
    //         --cef-host-protocol, 1, --assets-dir, <dir> (optional), NULL.
    std::vector<std::string> args_storage = {
        binary_path,
        "--cef-host-socket", socket_path,
        "--cef-host-capability", capability,
        "--cef-host-protocol", "1",
    };
    if (!assets_dir.empty()) {
        args_storage.push_back("--assets-dir");
        args_storage.push_back(assets_dir);
    }

    std::vector<char*> argv;
    argv.reserve(args_storage.size() + 1);
    for (auto& s : args_storage) {
        argv.push_back(const_cast<char*>(s.c_str()));
    }
    argv.push_back(nullptr);

    posix_spawn_file_actions_t fa;
    posix_spawn_file_actions_init(&fa);
    // Default behaviour: all FDs without FD_CLOEXEC are inherited. We marked
    // the listening socket with FD_CLOEXEC, so only stdio (0, 1, 2) leaks
    // into the child. No explicit addinherit needed.

    pid_t pid = -1;
    int rc = posix_spawn(&pid, binary_path.c_str(), &fa, nullptr,
                         argv.data(), environ);
    posix_spawn_file_actions_destroy(&fa);

    if (rc != 0) {
        if (err) *err = std::string("posix_spawn: ") + std::strerror(rc);
        return -1;
    }
    return pid;
}

int CompleteHandshake(int listen_fd,
                      const std::string& expected_capability,
                      uid_t expected_uid,
                      pid_t sidecar_pid,
                      std::string* err) {
    // Accept the sidecar's connection with a 5-second timeout.
    struct timeval tv;
    tv.tv_sec = 5;
    tv.tv_usec = 0;
    setsockopt(listen_fd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));

    int client_fd = accept(listen_fd, nullptr, nullptr);
    if (client_fd < 0) {
        if (err) *err = std::string("accept: ") + std::strerror(errno);
        if (sidecar_pid > 0) {
            kill(sidecar_pid, SIGKILL);
            int status;
            waitpid(sidecar_pid, &status, 0);
        }
        return -1;
    }
    SetSocketTimeout(client_fd, 5);

    struct ucred cred;
    socklen_t cred_len = sizeof(cred);
    if (getsockopt(client_fd, SOL_SOCKET, SO_PEERCRED, &cred, &cred_len) < 0) {
        if (err) *err = std::string("SO_PEERCRED: ") + std::strerror(errno);
        close(client_fd);
        if (sidecar_pid > 0) {
            kill(sidecar_pid, SIGKILL);
            int status;
            waitpid(sidecar_pid, &status, 0);
        }
        return -1;
    }
    if (cred.uid != expected_uid) {
        if (err) {
            *err = "uid mismatch: got " + std::to_string(cred.uid) +
                   ", expected " + std::to_string(expected_uid);
        }
        close(client_fd);
        if (sidecar_pid > 0) {
            kill(sidecar_pid, SIGKILL);
            int status;
            waitpid(sidecar_pid, &status, 0);
        }
        return -1;
    }

    std::string frame, recv_err;
    if (!RecvFrame(client_fd, &frame, &recv_err)) {
        if (err) *err = "recv hello: " + recv_err;
        close(client_fd);
        if (sidecar_pid > 0) {
            kill(sidecar_pid, SIGKILL);
            int status;
            waitpid(sidecar_pid, &status, 0);
        }
        return -1;
    }

    // Minimal JSON parse: extract capability and kind fields.
    std::string cap = ExtractJsonString(frame, "capability");
    if (cap != expected_capability) {
        if (err) *err = "capability mismatch (got " + cap + ")";
        close(client_fd);
        if (sidecar_pid > 0) {
            kill(sidecar_pid, SIGKILL);
            int status;
            waitpid(sidecar_pid, &status, 0);
        }
        return -1;
    }

    // Build ready envelope.
    std::string ready = R"({"v":1,"kind":1,"capability":")" + expected_capability +
                        R"(","hostPid":)" + std::to_string(getpid()) + "}";
    if (!SendFrame(client_fd, ready)) {
        if (err) *err = "send ready: write failed";
        close(client_fd);
        if (sidecar_pid > 0) {
            kill(sidecar_pid, SIGKILL);
            int status;
            waitpid(sidecar_pid, &status, 0);
        }
        return -1;
    }

    // Disable the timeouts; the channel is now established.
    tv.tv_sec = 0;
    tv.tv_usec = 0;
    setsockopt(client_fd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));
    setsockopt(client_fd, SOL_SOCKET, SO_SNDTIMEO, &tv, sizeof(tv));

    return client_fd;
}

void SendShutdownEnvelope(int client_fd, const std::string& capability,
                          const std::string& reason) {
    if (client_fd < 0) return;
    std::string env = R"({"v":1,"kind":6,"capability":")" + capability +
                      R"(","reason":")" + reason + R"("})";
    SendFrame(client_fd, env);
}

void TerminateSidecar(pid_t sidecar_pid) {
    if (sidecar_pid <= 0) return;
    kill(sidecar_pid, SIGTERM);
    for (int i = 0; i < 20; ++i) {
        int status;
        pid_t r = waitpid(sidecar_pid, &status, WNOHANG);
        if (r == sidecar_pid) return;
        if (r < 0) return;
        usleep(100000);  // 100ms
    }
    kill(sidecar_pid, SIGKILL);
    int status;
    waitpid(sidecar_pid, &status, 0);
}

SpawnResult SpawnAndHandshake(const std::string& argv0_path,
                               const std::string& assets_dir) {
    SpawnResult r;

    r.runtime_dir = CreateRuntimeDir();
    if (r.runtime_dir.empty()) {
        r.error_message = "failed to create runtime dir";
        return r;
    }

    int listen_fd = BindSidecarSocket(r.runtime_dir, &r.socket_path);
    if (listen_fd < 0) {
        r.error_message = "failed to bind sidecar socket at " + r.socket_path;
        rmdir(r.runtime_dir.c_str());
        return r;
    }
    r.client_fd = -1;

    r.capability = GenerateCapabilityToken();
    if (r.capability.empty()) {
        r.error_message = "failed to generate capability token";
        close(listen_fd);
        unlink(r.socket_path.c_str());
        rmdir(r.runtime_dir.c_str());
        return r;
    }

    std::string binary = FindSidecarBinary(argv0_path);
    if (binary.empty()) {
        r.error_message = "wails-go-runtime not found in $WAILS_CEF_SIDECAR, "
                          "argv0 directory, or $CEF_DIR";
        close(listen_fd);
        unlink(r.socket_path.c_str());
        rmdir(r.runtime_dir.c_str());
        return r;
    }

    std::string spawn_err;
    r.sidecar_pid = SpawnSidecar(binary, r.socket_path, r.capability,
                                  assets_dir, &spawn_err);
    if (r.sidecar_pid < 0) {
        r.error_message = "spawn failed: " + spawn_err;
        close(listen_fd);
        unlink(r.socket_path.c_str());
        rmdir(r.runtime_dir.c_str());
        return r;
    }

    std::string hs_err;
    r.client_fd = CompleteHandshake(listen_fd, r.capability, getuid(),
                                     r.sidecar_pid, &hs_err);
    close(listen_fd);  // No more inbound connections.

    if (r.client_fd < 0) {
        r.error_message = "handshake failed: " + hs_err;
        if (r.sidecar_pid > 0) {
            int status;
            waitpid(r.sidecar_pid, &status, 0);
            r.sidecar_pid = -1;
        }
        unlink(r.socket_path.c_str());
        rmdir(r.runtime_dir.c_str());
        return r;
    }

    r.ok = true;
    return r;
}

}  // namespace wails_cef